--create or replace function protect_sum_of_payments()
--returns trigger as $$
--begin
--    if current_setting('app.bypass_sum_of_payments', true) = 'on' then
--        return new;
--    end if;
--
--    raise exception 'Direct update of sum_of_payments is not allowed';
--end;
--$$ language plpgsql;